### ISSUE TITLE
Build on 4.10 fails

### ISSUE THREAD

**Issue by shefty** [hjelmn/xpmem#17]
This is from Ubuntu 16.04, which is based on 4.10.

```
xpmem_attach.c: In function xpmem_fault_handler:
xpmem_attach.c:172:41: error: struct vm_fault has no member named virtual_address
```
The kernel structure vm_fault changed from 4.9 to 4.10, replacing virtual_address with address.  The xpmem source traps for this >= kernel 4.11, but doesn't handle 4.10 correctly.  A quick attempt to change the kernel check from 4.11 to 4.10 did not work.

4.10 needs an xpmem_fault_handler() with 2 arguments, but the vaddr pulled from vmf->address.  I.e. the else check from line 162, but the if check from line 168.  Trying to select this option creates a duplicate variable (vma), and it's not clear to me which one to use.

**Comment by hjelmn** [comment]
Ok, I will look into this now.

**Comment by hjelmn** [comment]
Think I have it fixed. It now builds and runs in Ubuntu 16.04 with 4.10. Will merge the PR once CI completes.

**Comment by shefty** [comment]
thanks!

**Comment by hjelmn** [comment]
No problem. The kernel interfaces after being stable for a long time have been changing relatively rapidly lately. I just discovered that v4.12+ needs an additional fix due to the 5-level page tables. Have a PR open for that as well.
